### ISSUE TITLE
Startup fails with:  no function clause matching in Hulaaki.Decoder.decode_remaining_length/3

### ISSUE THREAD

**Issue by solars** [suvash/hulaaki#49] opened 2019-01-02 15:42 UTC
Hi there,

I've got the following setup:
https://gist.github.com/solars/bb067283acba6ef639201f703e81296a
It starts a client and a publisher in separate Genservers.

On my server it's working fine, however, locally if I start the application with iex -S mix I often get the following errors:

https://gist.github.com/solars/95851475a002cf5a71f0d5754893bfc8

Can anyone tell me what's going on here?
I'm having problems testing my application.

**Comment by solars** [comment] 2019-01-03 08:14
@suvash could you maybe tell me how to debug this?

**Comment by solars** [comment] 2019-01-29 08:49
I still have this problem, it must be related to Hulaaki - however, it only happens at home, it works in the office.
The ISP does not specifically block anything, so it would be interesting to find a way to debug this issue.

**Comment by suvash** [comment] 2019-01-29 10:48
oh, didn't see this message before.
whats the `options` that you're passing in to the client connect ?

**Comment by solars** [comment] 2019-01-30 08:41
@suvash no problem :)

The options I use are:

```
config :processor, Processor.MqttListener, [
  client_id: "cb_iex12533332",
  host: "eu.thethings.network",
  port: 1883,
  username: "xxx",
  password: "xxx",
  topics: ["+/devices/+/up"]
]
```

As you can see in the gists above, the client_id is not used at the moment as we are generating a UUID.

It's very weird, I can connect from our office, but from my home it doesn't work and results in the error above. I thought it might be a firewall issue but other clients work fine.

**Comment by solars** [comment] 2019-02-08 21:15
@suvash any idea?

**Comment by suvash** [comment] 2019-02-10 13:10
this is a tricky one. Unless you can find a way to reproduce this, it's hard for me to guess as to what it could be. But, as you mention, it seems to be somehow related to the network differences. I'd start there(if I could).

**Comment by solars** [comment] 2019-02-10 13:38
I can only reproduce it locally, it doesn't work here 100%.
The thing is I don't get any logs that are useful, so the question is, how can I output something meaningful or where should I start?

**Comment by suvash** [comment] 2019-02-10 14:42
So, I looked into the stack trace a bit.
From what I can deduce there, It seems like the CONNACK packet decoding is the issue. The code that fails is being called at https://github.com/suvash/hulaaki/blob/master/lib/hulaaki/decoder.ex#L139 
According to the spec, the second byte of this packet (remaining length) should have the value 2, but the code is failing because the second byte seems to be empty (as you can see in the stack trace, where the the byte to be decoded is simply empty ("")
```
** (FunctionClauseError) no function clause matching in Hulaaki.Decoder.decode_remaining_length/3
    (hulaaki) lib/hulaaki/decoder.ex:68: Hulaaki.Decoder.decode_remaining_length("", 0, 1)
(hulaaki) lib/hulaaki/decoder.ex:139: Hulaaki.Decoder.decode_connect_ack/1
```
So, at this point, I'm concluding that this a malformed CONNACK packet with missing second byte on the fixed header, and it cannot be decoded as per spec.
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180837

And, I have no idea why this is happening (why your server sends this malformed packet, or why it's being dropped/filtered on your network). To dig deeper, you'll have use a packet analyzer like Wireshark etc. and see what's happening there.

Let me know if manage to find something more.

**Comment by suvash** [comment] 2019-02-22 18:15
Closing this for now. But, feel free to add comments if you find a way to reproduce it, or any further info.

**Closed by suvash** 2019-02-22 18:15 UTC
