### ISSUE TITLE
App crashes when sending binary data

### ISSUE THREAD

**Issue by chintan-mishra** [suvash/hulaaki#39] opened 2018-02-24 03:40 UTC
Error
```
08:48:10.374 [error] GenServer #PID<0.237.0> terminating
** (FunctionClauseError) no function clause matching in Hulaaki.Message.publish/6
    (hulaaki) lib/hulaaki/message.ex:134: Hulaaki.Message.publish(4, "topic", <<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 255, 219, 0, 67, 0, 13, 9, 10, 11, 10, 8, 13, 11, 10, 11, 14, 14, 13, 15, 19, 32, 21, 19, 18, 18, 19, 39, 28, ...>>, 0, 1, 1)
    (test_app) lib/hulaaki/client.ex:136: TestApp.MQTT.Client.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.236.0>): {:publish, [topic: "topic", message: <<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 255, 219, 0, 67, 0, 13, 9, 10, 11, 10, 8, 13, 11, 10, 11, 14, 14, 13, 15, 19, 32, 21, 19, 18, 18, 19, 39, 28, ...>>, dup: 0, qos: 1, retain: 1]}
State: %{connection: #PID<0.238.0>, keep_alive_interval: 100000, keep_alive_timer_ref: #Reference<0.3454223284.3145728002.221071>, packet_id: 4, ping_response_timeout_interval: 200000, ping_response_timer_ref: nil, pub_sub_pid: #PID<0.236.0>}
Client #PID<0.236.0> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:827: GenServer.call/3
    (test_app) lib/test_app/mqtt/pub_sub.ex:96: TestApp.MQTT.PubSub.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

This is the code that handles publishing.
```
def handle_info({:pub_msg_to_topic, msg, topic}, state = %{mqtt_pid: mqtt_pid}) do
  pub_opts = [
    topic: topic,
    message: msg,
    dup: 0,
    qos: 1,
    retain: 1
  ]
  TestApp.MQTT.Client.publish(mqtt_pid, pub_opts)
  IO.puts "publishing msg on #{topic}"
  {:noreply, state}
end
```
The Hulaaki client, `TestApp.MQTT.Client`, in my Elixir app is exactly same as the one in the README file.

While subscribing the Hulaaki client works fine, as I am also sending binary data from the client. However, when I try to publish data, from the Elixir app, in form of binary then the app crashes. Any leads on how I might solve this issue?

How am I sending binary data?
```
msg = Msgpax.pack!(%{
  key1: value1,
  key2: value2,
  key3: <<binary3>>
}) |> IO.iodata_to_binary()

send publisher_pid, {:pub_msg_to_topic, msg, "topic"}
```

I am using VerneMQ broker 1.3.0, and Elixir 1.6 both have been compiled using Erlang 20.2.

**Comment by suvash** [comment] 2018-02-24 17:04
From the stack trace I see above, it seems like the message you've built (via Msgpax > ... ) is not a valid binary. The function clause matching is failing the test defined here. https://github.com/suvash/hulaaki/blob/master/lib/hulaaki/message.ex#L136

Can you double check if the msg you're building (`msg` as mentioned above) is a valid binary (using `is_binary(...)`). If it is a valid binary indeed, can you paste that here, so that I can reproduce this problem ?

**Comment by suvash** [comment] 2018-02-26 23:45
@chintan-mishra Please reply back with some info, else will be closing this in some more days.

**Comment by chintan-mishra** [comment] 2018-02-27 06:13
I hadn't had the time to check this out. I plan to check this out within
next 12-15 hrs. I'll edit this comment with update.

Thanks for bearing the delay.

**Comment by chintan-mishra** [comment] 2018-02-27 14:57
I hadn't had the time to check this out. I plan to check this out within
next 12-15 hrs. I'll edit this comment with an update.

Thanks for bearing the delay.

UPDATE:
I am getting the binary from a file. So this is what I am doing

```
iex> bin_file = "filename.jpg" |> File.read!
#REPL response
iex> msgpack_w_o_bin = Msgpax.pack!(%{request: "abc", abc: "success", abc_type: "new-file", abc_msg: file}) |> IO.iodata_to_binary
#REPL response
iex> msgpack_w_bin = Msgpax.pack!(%{request: "abc", abc: "success", abc_type: "new-file", abc_msg: Msgpax.Bin.new(file)}, iodata: false)
#REPL response
iex> is_binary(msgpack_w_bin)
true
iex> is_binary(msgpack_w_o_bin)
true
```

I also added `IO.puts is_binary(data_as_msg_pack)` in the function that publishes the data. It shows `true` in the terminal.

**Comment by suvash** [comment] 2018-02-27 15:46
and, I'm assuming the second one works `mgspack_w_bin` fine ?

**Comment by suvash** [comment] 2018-02-27 15:52
as you can see here in Msgpax docs, the right way to get the encoded term as binary. https://hexdocs.pm/msgpax/Msgpax.html#pack/2-options

**Comment by suvash** [comment] 2018-02-27 15:58
another application relevant optimization, it's not the best idea to use a message queue to send whole files, this breaks down at some point, instead better to send a link to the file (for eg. that's on S3 etc.) and keep your messages snappy, both for the producer as well as consumer.

**Comment by chintan-mishra** [comment] 2018-02-27 16:08
Didn't know about the message queue issue. The method stated by you seems good. I will switch to that.

I have not been able to verify if it works with `mgspack_w_bin`. I keep hitting `GenServer` timeout. I am working on it

**Comment by chintan-mishra** [comment] 2018-02-28 11:13
```
16:10:53.494 [error] GenServer #PID<0.214.0> terminating
** (stop) exited in: GenServer.call(#PID<0.219.0>, {:publish, [topic: "topic", message: <<132, 171, 105, 109, 103, 95, 115, 104, 97, 114, 105, 110, 103, 169, 114, 101, 99, 105, 112, 105, 101, 110, 116, 175, 105, 109, 103, 95, 115, 104, 97, 114, 105, 110, 103, 95, 109, 115, 103, 219, 0, 9, 241, 227, 255, 216, ...>>, dup: 0, qos: 1, retain: 1]}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:830: GenServer.call/3
    (test_app) lib/test_app/mqtt/pub_sub.ex:94: TestApp.MQTT.PubSub.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:pub_msg_to_topic, <<132, 171, 105, 109, 103, 95, 115, 104, 97, 114, 105, 110, 103, 169, 114, 101, 99, 105, 112, 105, 101, 110, 116, 175, 105, 109, 103, 95, 115, 104, 97, 114, 105, 110, 103, 95, 109, 115, 103, 219, 0, 9, 241, 227, 255, 216, 255, 224, ...>>, "topic"}
State: %{id: "#Reference<0.3970827293.80740353.21874>", mqtt_pid: #PID<0.219.0>, topic: "topic"}

16:10:53.497 [error] GenServer #PID<0.219.0> terminating
** (stop) exited in: GenServer.call(#PID<0.220.0>, {:publish, %Hulaaki.Message.Publish{dup: 0, id: 4, message: <<132, 171, 105, 109, 103, 95, 115, 104, 97, 114, 105, 110, 103, 169, 114, 101, 99, 105, 112, 105, 101, 110, 116, 175, 105, 109, 103, 95, 115, 104, 97, 114, 105, 110, 103, 95, 109, 115, 103, 219, 0, 9, 241, 227, 255, ...>>, qos: 1, retain: 1, topic: "topic", type: :PUBLISH}}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:830: GenServer.call/3
    (test_app) lib/hulaaki/client.ex:139: TestApp.MQTT.Client.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.214.0>): {:publish, [topic: "topic", message: <<132, 171, 105, 109, 103, 95, 115, 104, 97, 114, 105, 110, 103, 169, 114, 101, 99, 105, 112, 105, 101, 110, 116, 175, 105, 109, 103, 95, 115, 104, 97, 114, 105, 110, 103, 95, 109, 115, 103, 219, 0, 9, 241, 227, 255, 216, ...>>, dup: 0, qos: 1, retain: 1]}
State: %{connection: #PID<0.220.0>, keep_alive_interval: 100000, keep_alive_timer_ref: #Reference<0.3970827293.80740353.23386>, packet_id: 4, ping_response_timeout_interval: 200000, ping_response_timer_ref: nil, pub_sub_pid: #PID<0.214.0>}
Client #PID<0.214.0> is dead
```

I have been trying to find out a work around the `GenServer` time-out but I noticed that the process stops in 5-seconds. This might be due to no `GenServer` options available in [lib/hulaaki/client.ex#L25](https://github.com/suvash/hulaaki/blob/master/lib/hulaaki/client.ex#L25) which chooses the standard 5-second timeout options.

Any suggestion on how to overcome the timeout.

**Comment by suvash** [comment] 2018-02-28 14:03
I'm not sure I understand. The timeout is specified on the first connection (as it's applied on the connection level and is configurable), and not on the individual messages being sent. Also, the latest version has raised this limit https://github.com/suvash/hulaaki/blob/master/CHANGELOG.md#012---2018-02-07

**Comment by suvash** [comment] 2018-02-28 14:08
Also, please look into the test files for the individual modules. The entire codebase is well-tested, if you want to see example usage.

**Comment by chintan-mishra** [comment] 2018-02-28 17:02
I was referring to timeout defined in [here](https://hexdocs.pm/elixir/GenServer.html#call/3)

In [this function](https://github.com/suvash/hulaaki/blob/master/lib/hulaaki/client.ex#L25) `GenServer.call/3` timeout is set automatically to 5000ms, as it is not specified in the file. The synchronous `GenServer.call` waits for a response after which it timeouts, leaving the process incomplete.

I fixed this in my local copy of Hulaaki by simply replacing `GenServer.call(pid, {:publish, opts})` [here](https://github.com/suvash/hulaaki/blob/master/lib/hulaaki/client.ex#L26) with `GenServer.call(pid, {:publish, opts}, 15000)`. Now GenServer waits for 15-seconds before  giving this error.

I will inspect this further and provide details after which I will add timeout option in `GenServer.call/3` and open a pull request.

**Comment by suvash** [comment] 2018-02-28 23:50
So, as you can see the GenServer still error-ed out after 15 seconds. The problem isn't on the GenServer timeout (GenServers don't take that long to handle_call), unless you have some blocking action on the handle_call, which you absolutely should not have. Try not sending the file contents, but a short string. 

At this point, I'm pretty sure the issue is on the application code. If you gist the relevant parts of the application code somewhere, I can take a look at it when time permits.

I'll close this issue as of now. Please continue with the discussion. Once we figure out if there's a real issue, we can reopen this at a later point.

**Closed by suvash** 2018-02-28 23:50 UTC

**Comment by chintan-mishra** [comment] 2018-03-01 02:12
Closing remarks:

IMO, the issue isn't resolved.

`handle_call` occurs almost instantaneously.<How did I test this?--I am printing jibberish stuff in `handle_call` related to publishing in the lib.> What fails is that messages don't get published in poor internet connectivity.

I am using MQTT in a Nerves project where the device is expected to have poor internet connectivity. Sending data packets of size 90-120 kB at 10-15kB/s leads to this issue. It takes somewhere between 6-12 seconds to send the message but `GenServer` timeouts at 5 seconds which causes this issue. If the application has access to unthrottled speed then I don't have timeouts.

**Comment by suvash** [comment] 2018-03-01 22:26
Ok. Now, that's a much more clearly defined issue (and a different issue compared to title of this one). Please go ahead and open a new issue and also mention/copy this handle_call behaviour. If possible, please mention
- how you've simulated/reproduced this issue.  (how did you throttle connection speeds)
- how you managed to resolve it, if at all.

Feel free to submit a PR along if you've a solution. But, the two above points are more informative.
